'use client';
import {useEffect,useMemo,useState} from 'react';
import Header from '../../components/Header';
import {browserSupabase} from '../../lib/supabase';
import {scoreAssessment,ratingDescriptions} from '../../lib/scoring';
import {brands} from '../../lib/brands';

const initial={assessment_reason:'Preventative Maintenance',service_categories:[],property_name:'',management_company:'',owner_company:'',brand:'',property_category:'',property_city:'',property_state:'',contact_name:'',contact_email:'',contact_phone:'',total_rooms:'',last_renovated_year:'',rooms_available_per_day:'',floor_release_available:false,materials_owner_supplied:false,comp_rooms_available:false,meals_provided:false,room_release_notes:'',paint_score:3,caulk_score:3,furniture_score:3,hvac_score:3,plumbing_score:3,doors_score:3,logistics_score:3,room_release_score:3,top_issues:[],notes:''};
const reasons=['Preventative Maintenance','Budget Pricing','Capital Planning','Due Diligence','New Acquisition','PIP Planning','Mechanical Assessment','General Maintenance','Other'];
const cats=['Guestroom PM','Public Areas','Mechanical Systems','Capital Improvements','General Maintenance'];
const issues=['Heavy caulking needed','Widespread paint touch-ups','Corner-to-corner paint needed','Furniture touch-ups','PTAC/VTAC cleaning','Drain issues','Entry door painting','Grout refresh','Room release constraints','Mechanical concerns','Public area wear','Capital project needed'];
const fileLabels=['Main Room','Kitchen / Kitchenette (if applicable)','Bedroom Area','Bathroom','Bathroom Caulking Close-up','PTAC / VTAC / HVAC Unit','Furniture Damage','Entry Door','Public Area or Corridor','Mechanical Equipment','Video Walkthrough'];
const steps=['Reason','Property','Operations','Condition','Issues','Photos','Notes'];

export default function AssessmentPage(){
 const [form,setForm]=useState(initial);const [files,setFiles]=useState({});const[status,setStatus]=useState('');const[step,setStep]=useState(0);
 useEffect(()=>{const saved=localStorage.getItem('caliber_assessment_draft');if(saved)try{setForm({...initial,...JSON.parse(saved)})}catch{}},[]);
 useEffect(()=>{localStorage.setItem('caliber_assessment_draft',JSON.stringify(form))},[form]);
 const scored=useMemo(()=>scoreAssessment(form),[form]);
 function update(k,v){setForm(p=>({...p,[k]:v}))}
 function tog(k,v){setForm(p=>({...p,[k]:p[k].includes(v)?p[k].filter(x=>x!==v):[...p[k],v]}))}
 async function submit(e){e.preventDefault();setStatus('Submitting...');try{const supabase=browserSupabase();const id=crypto.randomUUID();const payload={id,...form,property_category:scored.property_category,total_rooms:Number(form.total_rooms),last_renovated_year:form.last_renovated_year?Number(form.last_renovated_year):null,rooms_available_per_day:form.rooms_available_per_day?Number(form.rooms_available_per_day):null,...scored};const{error}=await supabase.from('assessments').insert(payload);if(error)throw error;for(const[label,list]of Object.entries(files)){for(const file of list){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${id}/${label.replace(/[^a-zA-Z0-9._-]/g,'_')}_${Date.now()}_${safe}`;const up=await supabase.storage.from('assessment-media').upload(path,file);if(up.error)throw up.error;const row=await supabase.from('assessment_files').insert({assessment_id:id,file_label:label,file_name:file.name,file_path:path,file_type:file.type,file_size:file.size});if(row.error)throw row.error}}localStorage.removeItem('caliber_assessment_draft');window.location.href='/thank-you'}catch(err){setStatus(err.message||'Submission failed.')}}
 return <><Header/><main style={{maxWidth:980,margin:'0 auto',padding:'36px 20px 70px'}}>
  <p className="kicker">Caliber Property Assessment</p><h1 className="h1">Property Assessment</h1><p className="muted">This assessment helps Caliber review property condition, production cadence, scope requirements, and budgetary pricing.</p>
  <Progress step={step}/>
  <form onSubmit={submit} style={{display:'grid',gap:20,marginTop:24}}>
   {step===0&&<Card title="1. Reason for Assessment"><Select label="Primary Reason" value={form.assessment_reason} onChange={v=>update('assessment_reason',v)} options={reasons}/><p className="label" style={{marginTop:16}}>Service Categories</p><Chips items={cats} selected={form.service_categories} onClick={v=>tog('service_categories',v)}/></Card>}
   {step===1&&<Card title="2. Property Information"><Grid><Field label="Property Name" required value={form.property_name} onChange={v=>update('property_name',v)}/><Field label="Management Company" value={form.management_company} onChange={v=>update('management_company',v)}/><Field label="Ownership Group" value={form.owner_company} onChange={v=>update('owner_company',v)}/><Select label="Brand" value={form.brand} onChange={v=>update('brand',v)} options={['',...brands]}/><Field label="City" value={form.property_city} onChange={v=>update('property_city',v)}/><Field label="State" value={form.property_state} onChange={v=>update('property_state',v)}/><Field label="Total Rooms" type="number" required value={form.total_rooms} onChange={v=>update('total_rooms',v)}/><Field label="Last Renovated Year" type="number" value={form.last_renovated_year} onChange={v=>update('last_renovated_year',v)}/></Grid>{form.brand&&<p style={{marginTop:14}}><span className="badge">Auto Category: {scored.property_category}</span></p>}</Card>}
   {step===2&&<Card title="3. Contact and Operations"><Grid><Field label="Contact Name" required value={form.contact_name} onChange={v=>update('contact_name',v)}/><Field label="Contact Email" type="email" required value={form.contact_email} onChange={v=>update('contact_email',v)}/><Field label="Contact Phone" value={form.contact_phone} onChange={v=>update('contact_phone',v)}/><Field label="Rooms Available Per Day" type="number" value={form.rooms_available_per_day} onChange={v=>update('rooms_available_per_day',v)}/></Grid><div className="grid4" style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12,marginTop:16}}><Toggle label="Floor Release Available" value={form.floor_release_available} onChange={v=>update('floor_release_available',v)}/><Toggle label="Owner Supplies Materials" value={form.materials_owner_supplied} onChange={v=>update('materials_owner_supplied',v)}/><Toggle label="Comp Rooms Available" value={form.comp_rooms_available} onChange={v=>update('comp_rooms_available',v)}/><Toggle label="Meals Provided" value={form.meals_provided} onChange={v=>update('meals_provided',v)}/></div><TextArea label="Room Release Notes" value={form.room_release_notes} onChange={v=>update('room_release_notes',v)}/></Card>}
   {step===3&&<Card title="4. Condition Ratings"><p className="muted">Use 5 for good condition and 1 for worst condition. Guidance changes with each rating.</p><Grid>{['paint','caulk','furniture','hvac','plumbing','doors','logistics','room_release'].map(k=><Score key={k} name={k} label={k.replace('_',' ')} value={form[`${k}_score`]} onChange={v=>update(`${k}_score`,Number(v))}/>)}</Grid><div style={{background:'#EAF4FF',borderRadius:16,padding:18,marginTop:18}}><strong style={{color:'#0B2F5B'}}>Internal Preview: {scored.readiness_score}/100</strong><p>Program: {scored.recommended_program}</p><p>Production: {scored.estimated_rooms_per_day} rooms/day</p></div></Card>}
   {step===4&&<Card title="5. Top Issues"><Chips items={issues} selected={form.top_issues} onClick={v=>tog('top_issues',v)}/></Card>}
   {step===5&&<Card title="6. Photos and Videos"><p className="muted">Upload current photos. On mobile, these fields can open the camera or photo library.</p><Grid>{fileLabels.map(label=><label key={label} style={{border:'1px dashed #cbd5e1',borderRadius:16,padding:14,background:'#f8fafc'}}><strong style={{color:'#0B2F5B'}}>{label}</strong><input style={{marginTop:10,display:'block'}} type="file" multiple accept="image/*,video/*" capture="environment" onChange={e=>setFiles(p=>({...p,[label]:Array.from(e.target.files||[])}))}/></label>)}</Grid></Card>}
   {step===6&&<Card title="7. Additional Notes"><TextArea label="Notes" value={form.notes} onChange={v=>update('notes',v)}/><div style={{background:'#f8fafc',padding:16,borderRadius:14,marginTop:16}}><strong>Ready to submit?</strong><p className="muted">Caliber will review the assessment, uploaded photos, and operational notes.</p></div></Card>}
   <div style={{display:'flex',justifyContent:'space-between',gap:12}}>
    <button className="btn-secondary" type="button" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}>Back</button>
    {step<steps.length-1?<button className="btn-primary" type="button" onClick={()=>setStep(Math.min(steps.length-1,step+1))}>Next</button>:<button className="btn-primary" type="submit">Submit Property Assessment</button>}
   </div>
   {status&&<div className="card" style={{padding:18,color:'#b42318',fontWeight:800}}>{status}</div>}
  </form>
 </main></>
}
function Progress({step}){const pct=Math.round(((step+1)/steps.length)*100);return <div style={{marginTop:20}}><div style={{display:'flex',justifyContent:'space-between',fontWeight:800,color:'#0B2F5B'}}><span>Step {step+1} of {steps.length}: {steps[step]}</span><span>{pct}%</span></div><div style={{height:10,background:'#e2e8f0',borderRadius:999,marginTop:8}}><div style={{height:'100%',width:`${pct}%`,background:'#0F67B1',borderRadius:999}}/></div></div>}
function Card({title,children}){return <section className="card" style={{padding:24}}><h2 style={{color:'#0B2F5B',margin:'0 0 18px',fontWeight:900}}>{title}</h2>{children}</section>}
function Grid({children}){return <div className="grid2" style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:16}}>{children}</div>}
function Field({label,value,onChange,type='text',required=false}){return <label><span className="label">{label}{required?' *':''}</span><input className="input" type={type} required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options}){return <label><span className="label">{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o||'Select'}</option>)}</select></label>}
function TextArea({label,value,onChange}){return <label style={{display:'block',marginTop:16}}><span className="label">{label}</span><textarea style={{minHeight:100}} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Chips({items,selected,onClick}){return <div style={{display:'flex',flexWrap:'wrap',gap:8}}>{items.map(item=><button key={item} type="button" onClick={()=>onClick(item)} style={{borderRadius:999,border:'1px solid #cbd5e1',padding:'9px 12px',fontWeight:700,background:selected.includes(item)?'#0B2F5B':'white',color:selected.includes(item)?'white':'#334155'}}>{item}</button>)}</div>}
function Toggle({label,value,onChange}){return <button type="button" onClick={()=>onChange(!value)} style={{padding:14,borderRadius:12,border:'1px solid #cbd5e1',background:value?'#EAF4FF':'white',color:'#0B2F5B',fontWeight:800,textAlign:'left'}}>{value?'Yes':'No'}<br/><span style={{fontSize:12,color:'#64748b'}}>{label}</span></button>}
function Score({name,label,value,onChange}){const d=ratingDescriptions[name]?.[value]||'';return <label><span className="label" style={{textTransform:'capitalize'}}>{label}: {value}</span><input type="range" min="1" max="5" value={value} onChange={e=>onChange(e.target.value)}/><small style={{display:'block',color:'#64748b',lineHeight:1.4,marginTop:6}}>{d}</small></label>}
