export const SERVICE_CONFIG={
'Guestroom PM':{scores:[['paint_score','Paint'],['caulk_score','Caulking'],['furniture_score','Furniture'],['hvac_score','HVAC / PTAC'],['plumbing_score','Plumbing'],['doors_score','Doors'],['logistics_score','Logistics'],['room_release_score','Room Release']],photos:['Main Room','Kitchen / Kitchenette (if applicable)','Bedroom Area','Bathroom','Bathroom Caulking Close-up','PTAC / VTAC / HVAC Unit','Furniture Damage','Entry Door','Video Walkthrough']},
'Public Areas':{scores:[['main_area_paint_score','Main Area Paint'],['public_caulk_score','Caulk'],['drywall_score','Drywall'],['baseboards_score','Baseboards'],['exterior_condition_score','Exterior Condition / Sidewalk / Patio'],['upholstery_score','Upholstery'],['vinyl_wallpaper_score','Vinyl / Wallpaper']],photos:['Main Lobby','Corridors','Exterior / Sidewalk / Patio','Lighting','HVAC / Ceiling Diffusers','Restrooms','Elevators','Dining / Breakfast Area','Meeting Room / Common Area','Other Public Area']},
'Mechanical Systems':{scores:[['hvac_equipment_score','HVAC Equipment'],['ice_machine_score','Ice Machines'],['walkin_cooler_score','Walk-in Coolers / Freezers'],['reachin_equipment_score','Reach-ins'],['kitchen_equipment_score','Kitchen Equipment'],['laundry_equipment_score','Laundry Equipment'],['mechanical_access_score','Mechanical Access / Serviceability']],photos:['HVAC Equipment','Ice Machines','Walk-in Cooler / Freezer','Reach-in Equipment','Kitchen Equipment','Laundry Equipment','Mechanical Room','Condensers / Rooftop Units','Equipment Data Plates','Video Walkthrough']},
'Capital Improvements':{scores:[['paint_score','Paint / Finish Condition'],['drywall_score','Drywall / Substrate'],['flooring_score','Flooring'],['baseboards_score','Baseboards / Trim'],['fixtures_score','Fixtures'],['exterior_condition_score','Exterior / Envelope'],['logistics_score','Logistics / Access']],photos:['Primary Work Area','Walls / Drywall','Flooring','Fixtures','Exterior','Access / Logistics','Other Capital Scope','Video Walkthrough']},
'General Maintenance':{scores:[['paint_score','Paint'],['drywall_score','Drywall'],['plumbing_score','Plumbing'],['doors_score','Doors / Hardware'],['fixtures_score','Fixtures'],['logistics_score','Logistics']],photos:['Main Issue','Close-up Detail','Area Context','Access / Logistics','Other Issue','Video Walkthrough']}
};

const D={5:'Excellent. Little or no visible work is expected.',4:'Good. Minor touch-up or routine PM is expected.',3:'Fair. Visible wear and moderate maintenance are expected.',2:'Poor. Significant work is likely and production may slow.',1:'Very poor. Heavy repair, replacement, or custom scope is likely.'};

export const SCORE_DESCRIPTIONS={
default:D,
paint_score:{5:'Recently painted or in excellent condition.',4:'Minor paint touch-ups only.',3:'Moderate touch-ups in common wear areas.',2:'Heavy touch-ups required in many rooms.',1:'Extensive repainting likely throughout the assessed areas.'},
main_area_paint_score:{5:'Public area paint presents very well with little or no work needed.',4:'Minor touch-ups in isolated public areas.',3:'Moderate wear consistent with normal public area use.',2:'Heavy touch-ups across multiple public areas.',1:'Extensive public area repainting is likely required.'},
caulk_score:{5:'Caulk is clean, intact, and requires little or no replacement.',4:'Minor caulk touch-ups only.',3:'Some caulk replacement is expected during PM.',2:'Significant cracking, separation, discoloration, or missing caulk.',1:'Most wet areas likely require full caulk removal and replacement.'},
public_caulk_score:{5:'Public area caulk and sealant appear clean and intact.',4:'Minor sealant touch-ups only.',3:'Some public area caulk or sealant repair is needed.',2:'Multiple public areas show failing or discolored sealant.',1:'Widespread public area sealant replacement is likely required.'},
furniture_score:{5:'Furniture is in excellent condition.',4:'Minor tightening or touch-up only.',3:'Typical tightening, adjustment, or minor repair is needed.',2:'Many loose, damaged, or visibly worn items are present.',1:'Extensive repair, refinishing, or replacement is likely required.'},
upholstery_score:{5:'Upholstery is clean and presents well.',4:'Minor spotting or touch-up cleaning only.',3:'Moderate wear or cleaning is needed.',2:'Heavy staining, wear, or multiple damaged areas are present.',1:'Replacement or major restoration is likely required.'},
vinyl_wallpaper_score:{5:'Vinyl or wallpaper is clean, tight, and in excellent condition.',4:'Minor peeling or touch-up only.',3:'Moderate wear, seam issues, or localized repairs are needed.',2:'Multiple damaged, peeling, or stained areas are present.',1:'Widespread replacement or major wall finish repair is likely.'},
hvac_score:{5:'Units appear clean, maintained, and operating well.',4:'Minor servicing or filter cleaning only.',3:'Standard preventative maintenance is required.',2:'Heavy cleaning or multiple service issues are expected.',1:'Repair, deep cleaning, or replacement review may be required.'},
hvac_equipment_score:{5:'Mechanical equipment appears well maintained and operating properly.',4:'Recently serviced with only minor PM needed.',3:'Standard preventative maintenance is needed.',2:'Heavy PM, cleaning, or multiple repairs are expected.',1:'Significant repair or replacement may be required.'},
ice_machine_score:{5:'Ice machines appear clean and operating properly.',4:'Minor cleaning or service check is needed.',3:'Standard PM and sanitization are needed.',2:'Heavy cleaning, scale, leaks, or service issues are expected.',1:'Major cleaning, repair, or replacement review is likely.'},
walkin_cooler_score:{5:'Walk-ins appear clean, holding temperature, and well maintained.',4:'Minor PM or gasket adjustment only.',3:'Standard refrigeration PM is needed.',2:'Heavy PM, gasket, fan, drain, or temperature concerns are expected.',1:'Major repair or reliability concerns are likely.'},
reachin_equipment_score:{5:'Reach-ins appear clean and operating well.',4:'Minor service or cleaning only.',3:'Standard PM and coil cleaning are likely needed.',2:'Multiple units show service or reliability concerns.',1:'Major repair or replacement review is likely.'},
kitchen_equipment_score:{5:'Kitchen equipment appears maintained and operating well.',4:'Minor PM or adjustment only.',3:'Standard PM and service review are needed.',2:'Multiple service issues or heavy cleaning are likely.',1:'Major repair or specialty service is likely required.'},
laundry_equipment_score:{5:'Laundry equipment appears maintained and operating well.',4:'Minor PM or cleaning only.',3:'Standard PM and lint or vent review are needed.',2:'Multiple units show wear or service concerns.',1:'Major repair or replacement review is likely.'},
mechanical_access_score:{5:'Equipment access is clear and serviceable.',4:'Minor access limitations only.',3:'Some access coordination or staging may be needed.',2:'Access limitations will slow production or service.',1:'Poor access creates major service, safety, or production constraints.'},
plumbing_score:{5:'Fixtures and drains appear to be in excellent working condition.',4:'Minor adjustments or routine checks only.',3:'Typical PM with occasional fixture or drain repairs.',2:'Frequent plumbing repairs or slow drains are anticipated.',1:'Widespread plumbing issues, leaks, or failed fixtures are likely.'},
doors_score:{5:'Doors and hardware operate well and present cleanly.',4:'Minor tightening or adjustment only.',3:'Typical PM adjustments and hardware tightening are needed.',2:'Numerous doors or hardware items need repair.',1:'Extensive door, frame, or hardware repair is likely.'},
drywall_score:{5:'Drywall appears clean with little or no repair needed.',4:'Minor patching or touch-up only.',3:'Moderate patching and finish repair are needed.',2:'Multiple damaged areas or larger repairs are expected.',1:'Extensive drywall repair or replacement is likely.'},
baseboards_score:{5:'Baseboards and trim are in excellent condition.',4:'Minor touch-ups or reattachment only.',3:'Moderate wear or repair is needed.',2:'Multiple damaged or loose sections are present.',1:'Widespread replacement or major trim repair is likely.'},
exterior_condition_score:{5:'Exterior, sidewalks, or patio areas present very well.',4:'Minor cleaning or touch-up repairs only.',3:'Average condition with routine maintenance needed.',2:'Heavy weathering or multiple deficiencies are present.',1:'Major deterioration requiring significant repair is present.'},
flooring_score:{5:'Flooring is in excellent condition.',4:'Minor spot repair or cleaning only.',3:'Moderate wear or localized repair is needed.',2:'Multiple damaged or worn areas likely require repair.',1:'Replacement or major flooring work is likely required.'},
fixtures_score:{5:'Fixtures are in excellent condition and operating well.',4:'Minor adjustment or tightening only.',3:'Standard PM or minor parts replacement is needed.',2:'Multiple fixtures need repair or replacement.',1:'Major fixture replacement or specialty repair is likely.'},
logistics_score:{5:'Excellent access, staging, and coordination. Production should be efficient.',4:'Good access and staging with minor coordination needs.',3:'Some access, staging, or coordination issues may affect production.',2:'Limited access or poor staging will likely reduce productivity.',1:'Major logistics constraints will significantly affect schedule and labor.'},
room_release_score:{5:'Excellent floor-by-floor or block release allowing maximum production.',4:'Good room release with grouped work areas.',3:'Moderate room release with some grouping possible.',2:'Limited room blocks are available and productivity will likely be affected.',1:'Scattered rooms, frequent interruptions, or very limited daily access.'}
};

export function getScoreDescription(key,value){return SCORE_DESCRIPTIONS[key]?.[value]||SCORE_DESCRIPTIONS.default[value]||''}
export function getServiceConfig(categories=[]){return SERVICE_CONFIG[(categories||[])[0]]||SERVICE_CONFIG['Guestroom PM']}
